Implement app header
machinegrooving/linguicator-editor pull request #2
Opened 2020-02-23 18:24 UTC by dmrib

Depends on #1 .

2020-03-05 21:56 UTC, HeitorBoschirolli reviewed
There will be no version update commit?

2020-03-05 22:05 UTC, HeitorBoschirolli requested changes
Just one more thing

2020-03-05 22:05 UTC, HeitorBoschirolli commented on linguicator-editor/src/App.js
>  function App() {
What do you think about adding a comment describing each component describing what will be rendered?

2020-03-12 10:47 UTC, dmrib commented on linguicator-editor/src/App.js
>  function App() {
Done!

2020-03-16 11:48 UTC, HeitorBoschirolli reviewed
What do you think about renaming `src/components/Header/Header.js` to `src/components/Header/index.js`?

2020-03-17 11:52 UTC, HeitorBoschirolli approved these changes
+1

2020-03-17 11:54 UTC, merged