Render markdown preview
machinegrooving/linguicator-editor pull request #6
Opened 2020-03-01 13:42 UTC by dmrib

Depends on #5

2020-03-05 22:11 UTC, HeitorBoschirolli requested changes
Also missing the version update.

2020-03-05 22:11 UTC, HeitorBoschirolli commented on linguicator-editor/src/components/Content/Content.js
> +     * Returns:
what about using jsdoc to document the functions? Seems to be the most popular choice.

2020-03-16 11:32 UTC, HeitorBoschirolli commented
Didn't quite got the difference between this PR and [this one](https://github.com/machinegrooving/linguicator-editor/pull/8/)

2020-03-16 11:36 UTC, HeitorBoschirolli commented
+1

2020-03-16 23:31 UTC, dmrib commented on linguicator-editor/src/components/Content/Content.js
> +     * Returns:
Done.

2020-03-20 23:09 UTC, HeitorBoschirolli approved these changes
+1

2020-03-20 23:09 UTC, merged